import type { PlanningSnapshot } from "./types";
import { defaultHoraires, defaultHorairesEmploye } from "./engine/hours";
import { ordreAffichageFromNom } from "./display-order";

const IDS = {
  jonathan: "11111111-1111-4111-8111-111111111111",
  michael: "22222222-2222-4222-8222-222222222222",
  alexis: "33333333-3333-4333-8333-333333333333",
  romain: "44444444-4444-4444-8444-444444444444",
  raphael: "55555555-5555-4555-8555-555555555555",
  ethan: "66666666-6666-4666-8666-666666666666",
  louison: "77777777-7777-4777-8777-777777777777",
  quentin: "88888888-8888-4888-8888-888888888888",
  dupont: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1",
  martin: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa2",
  lefevre: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa3",
  pergola: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbb1",
  portail: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbb2",
  rampe: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbb3",
  table: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbb4",
};

export function createSeedSnapshot(): PlanningSnapshot {
  return {
    employees: [
      {
        id: IDS.jonathan,
        nom: "Jonathan",
        roles: ["administratif"],
        actif: true,
        is_admin: true,
        ordre_affichage: ordreAffichageFromNom("Jonathan"),
        horaires: defaultHorairesEmploye(),
      },
      {
        id: IDS.michael,
        nom: "Michael",
        roles: ["administratif"],
        actif: true,
        is_admin: true,
        ordre_affichage: ordreAffichageFromNom("Michael"),
        horaires: defaultHorairesEmploye(),
      },
      {
        id: IDS.alexis,
        nom: "Alexis",
        roles: ["fabrication", "pose"],
        actif: true,
        is_admin: true,
        ordre_affichage: ordreAffichageFromNom("Alexis"),
        horaires: defaultHorairesEmploye(),
      },
      {
        id: IDS.romain,
        nom: "Romain",
        roles: ["fabrication", "pose"],
        actif: true,
        ordre_affichage: ordreAffichageFromNom("Romain"),
        horaires: defaultHorairesEmploye(),
      },
      {
        id: IDS.raphael,
        nom: "Raphaël",
        roles: ["fabrication", "pose"],
        actif: true,
        ordre_affichage: ordreAffichageFromNom("Raphaël"),
        horaires: defaultHorairesEmploye(),
      },
      {
        id: IDS.ethan,
        nom: "Ethan",
        roles: ["fabrication", "pose"],
        actif: true,
        ordre_affichage: ordreAffichageFromNom("Ethan"),
        horaires: defaultHorairesEmploye(),
      },
      {
        id: IDS.louison,
        nom: "Louison",
        roles: ["fabrication", "pose"],
        actif: true,
        ordre_affichage: ordreAffichageFromNom("Louison"),
        horaires: defaultHorairesEmploye(),
      },
      {
        id: IDS.quentin,
        nom: "Quentin (apprenti)",
        roles: ["fabrication", "pose"],
        actif: true,
        ordre_affichage: ordreAffichageFromNom("Quentin (apprenti)"),
        horaires: defaultHorairesEmploye({ skipWednesday: true }),
      },
    ],
    chantiers: [
      {
        id: IDS.dupont,
        nom_client: "Dupont",
        adresse: "12 rue des Forges, 76200 Dieppe",
        lien_dossier_onedrive: "https://onedrive.example/dupont",
        priorite: "prioritaire",
        date_creation: "2026-09-01",
      },
      {
        id: IDS.martin,
        nom_client: "Martin",
        adresse: "8 chemin du Port, 76400 Fécamp",
        lien_dossier_onedrive: null,
        priorite: "normal",
        date_creation: "2026-09-03",
      },
      {
        id: IDS.lefevre,
        nom_client: "Lefèvre",
        adresse: "3 place de l'Église, 76550 Offranville",
        lien_dossier_onedrive: "https://onedrive.example/lefevre",
        priorite: "pas_presse",
        date_creation: "2026-09-05",
      },
    ],
    elements: [
      { id: IDS.pergola, chantier_id: IDS.dupont, nom_element: "Pergola" },
      { id: IDS.portail, chantier_id: IDS.dupont, nom_element: "Portail" },
      { id: IDS.rampe, chantier_id: IDS.martin, nom_element: "Rampe" },
      { id: IDS.table, chantier_id: IDS.lefevre, nom_element: "Table" },
    ],
    phases: [
      {
        id: "ccccccc1-cccc-4ccc-8ccc-ccccccccccc1",
        element_id: IDS.pergola,
        type_phase: "administratif",
        duree_estimee_heures: 8,
        date_debut: "2026-09-07",
        date_fin: "2026-09-07",
        employe_id: IDS.jonathan,
        statut: "en_cours",
        urgent: true,
      },
      {
        id: "ccccccc1-cccc-4ccc-8ccc-ccccccccccc2",
        element_id: IDS.pergola,
        type_phase: "fabrication",
        duree_estimee_heures: 24,
        date_debut: "2026-09-08",
        date_fin: "2026-09-10",
        employe_id: IDS.alexis,
        statut: "a_faire",
        urgent: true,
      },
      {
        id: "ccccccc1-cccc-4ccc-8ccc-ccccccccccc3",
        element_id: IDS.pergola,
        type_phase: "logistique",
        duree_estimee_heures: 16,
        date_debut: "2026-09-11",
        date_fin: "2026-09-14",
        employe_id: null,
        statut: "a_faire",
        urgent: false,
      },
      {
        id: "ccccccc1-cccc-4ccc-8ccc-ccccccccccc4",
        element_id: IDS.pergola,
        type_phase: "pose",
        duree_estimee_heures: 16,
        date_debut: "2026-09-15",
        date_fin: "2026-09-16",
        employe_id: IDS.alexis,
        statut: "a_faire",
        urgent: false,
      },
      {
        id: "ccccccc2-cccc-4ccc-8ccc-ccccccccccc1",
        element_id: IDS.portail,
        type_phase: "administratif",
        duree_estimee_heures: 4,
        date_debut: "2026-09-08",
        date_fin: "2026-09-08",
        employe_id: IDS.michael,
        statut: "a_faire",
        urgent: false,
      },
      {
        id: "ccccccc2-cccc-4ccc-8ccc-ccccccccccc2",
        element_id: IDS.portail,
        type_phase: "fabrication",
        duree_estimee_heures: 16,
        date_debut: "2026-09-09",
        date_fin: "2026-09-10",
        employe_id: IDS.romain,
        statut: "a_faire",
        urgent: false,
      },
      {
        id: "ccccccc2-cccc-4ccc-8ccc-ccccccccccc3",
        element_id: IDS.portail,
        type_phase: "logistique",
        duree_estimee_heures: 8,
        date_debut: "2026-09-15",
        date_fin: "2026-09-15",
        employe_id: null,
        statut: "a_faire",
        urgent: false,
      },
      {
        id: "ccccccc2-cccc-4ccc-8ccc-ccccccccccc4",
        element_id: IDS.portail,
        type_phase: "pose",
        duree_estimee_heures: 8,
        date_debut: "2026-09-17",
        date_fin: "2026-09-17",
        employe_id: IDS.romain,
        statut: "a_faire",
        urgent: false,
      },
      {
        id: "ccccccc3-cccc-4ccc-8ccc-ccccccccccc1",
        element_id: IDS.rampe,
        type_phase: "administratif",
        duree_estimee_heures: 4,
        date_debut: "2026-09-09",
        date_fin: "2026-09-09",
        employe_id: IDS.jonathan,
        statut: "a_faire",
        urgent: false,
      },
      {
        id: "ccccccc3-cccc-4ccc-8ccc-ccccccccccc2",
        element_id: IDS.rampe,
        type_phase: "fabrication",
        duree_estimee_heures: 16,
        date_debut: "2026-09-11",
        date_fin: "2026-09-14",
        employe_id: IDS.raphael,
        statut: "a_faire",
        urgent: false,
      },
      {
        id: "ccccccc3-cccc-4ccc-8ccc-ccccccccccc3",
        element_id: IDS.rampe,
        type_phase: "logistique",
        duree_estimee_heures: 8,
        date_debut: "2026-09-16",
        date_fin: "2026-09-16",
        employe_id: null,
        statut: "a_faire",
        urgent: false,
      },
      {
        id: "ccccccc3-cccc-4ccc-8ccc-ccccccccccc4",
        element_id: IDS.rampe,
        type_phase: "pose",
        duree_estimee_heures: 8,
        date_debut: "2026-09-18",
        date_fin: "2026-09-18",
        employe_id: IDS.ethan,
        statut: "a_faire",
        urgent: false,
      },
      {
        id: "ccccccc4-cccc-4ccc-8ccc-ccccccccccc1",
        element_id: IDS.table,
        type_phase: "administratif",
        duree_estimee_heures: 2,
        date_debut: "2026-09-10",
        date_fin: "2026-09-10",
        employe_id: IDS.michael,
        statut: "a_faire",
        urgent: false,
      },
      {
        id: "ccccccc4-cccc-4ccc-8ccc-ccccccccccc2",
        element_id: IDS.table,
        type_phase: "fabrication",
        duree_estimee_heures: 12,
        date_debut: "2026-09-15",
        date_fin: "2026-09-16",
        employe_id: IDS.louison,
        statut: "a_faire",
        urgent: false,
      },
      {
        id: "ccccccc4-cccc-4ccc-8ccc-ccccccccccc3",
        element_id: IDS.table,
        type_phase: "logistique",
        duree_estimee_heures: 8,
        date_debut: "2026-09-17",
        date_fin: "2026-09-17",
        employe_id: null,
        statut: "a_faire",
        urgent: false,
      },
      {
        id: "ccccccc4-cccc-4ccc-8ccc-ccccccccccc4",
        element_id: IDS.table,
        type_phase: "pose",
        duree_estimee_heures: 4,
        date_debut: "2026-09-21",
        date_fin: "2026-09-21",
        employe_id: IDS.quentin,
        statut: "a_faire",
        urgent: false,
      },
    ],
    absences: [
      {
        id: "dddddddd-dddd-4ddd-8ddd-ddddddddddd1",
        employe_id: IDS.ethan,
        date_debut: "2026-09-10",
        date_fin: "2026-09-11",
        type: "conge",
      },
    ],
    signalements: [],
    receptions: [],
    horaires: defaultHoraires(),
  };
}

export function createEmptySnapshot(): PlanningSnapshot {
  return {
    employees: [],
    chantiers: [],
    elements: [],
    phases: [],
    absences: [],
    signalements: [],
    receptions: [],
    horaires: defaultHoraires(),
  };
}
